### ISSUE TITLE
Disable unicode translation option

### ISSUE THREAD

**Issue by VasylSamoilov** [jhpyle/mTCP#1]
Is it possible to disable unicode translation? When I use LANG=C it prints out all escape sequences. 
example:
![image](https://user-images.githubusercontent.com/20946668/83560517-0edaa200-a51f-11ea-89af-b2b034f2a8e1.png)

**Comment by jhpyle** [comment]
The trouble with runtime options is that they increase the number of if/else statements that have to run when incoming bytes are processed, which slows the computer down, or they result in a larger .EXE file.  So I'd rather not create a runtime option.

Anyway, I recompiled the Telnet application without Unicode conversion, so you can try [NOUTF8.EXE](https://github.com/jhpyle/mTCP/blob/master/MTCP/APPS/TELNET/NOUTF8.EXE) and see if that makes a difference.

I suspect there is something else going on, though.  I can use `LC_ALL=C` without any issues.  It simply has the effect of causing some applications to avoid sending UTF8 to the terminal.

It is as though byte 0x1b (ESC) is being converted into a unicode sequence, or at least into a byte with a value larger than 0x7f.  I don't know what would cause that.

What command did you run that produced that output?  What is your `TERM` variable?  Are you setting any special telnet-related options in MTCP.CFG?  Are you able to run the original mTCP without any issues?

Hopefully the graphics will work.  Your machine seems to be compatible with CGA, so maybe `show --mono --cga` will work best.  Seems like a really cool device.  I assume you have Ethernet on PCMCIA?  I have one of those cards somewhere.

**Comment by VasylSamoilov** [comment]
NOUTF8 binary makes no difference.
![image](https://user-images.githubusercontent.com/20946668/83758040-13679d80-a67a-11ea-98c6-65ed507a7bde.png)

**Comment by VasylSamoilov** [comment]
mTCP telnet works fine with terminal pcansi-mono, to be specific. For this telnet I use TELNET_CGA 1 option and installed ansi terminal as in Readme.

**Comment by VasylSamoilov** [comment]
I compress binaries with upx, if it matters, because I have only 300kb of ram drive and pcmcia slot is used by network card.

**Comment by jhpyle** [comment]
When using the modified telnet, does it make any difference if you set `TERM=pcansi-mono` as opposed to`TERM=ansi`?

**Comment by VasylSamoilov** [comment]
pretty much the same, but missing color escape codes
![image](https://user-images.githubusercontent.com/20946668/83763019-e36fc880-a680-11ea-82fa-9c82ba2ab040.png)

**Comment by VasylSamoilov** [comment]
For comparison, this is stock mTCP telnet with pcansi-mono and CP866 ukrainian code page. There are some errors in displaying "і" letter, but I can't even begin to imagine why. It should either show them, or corrupt them, but not on one screen. Strange. This is probably midnight commander specific.
![image](https://user-images.githubusercontent.com/20946668/83763614-93453600-a681-11ea-9a5e-b047f28a8b18.png)

**Comment by jhpyle** [comment]
I updated [NOUTF8.EXE](https://github.com/jhpyle/mTCP/blob/master/MTCP/APPS/TELNET/NOUTF8.EXE).  Could you try this version and let me know if Midnight Commander works with `LC_ALL=C`?

Another thing you could try is to not set `LC_ALL=C`, but rather set your locale to `uk_UA.UTF-8` and then use the normal version of `TELNET.EXE` from this repository.  Then maybe Midnight Commander would work right.

The Unicode conversion in `TELNET.EXE` in this repository is for Code Page 437.  If you are using Code Page 866 on your device, the wrong bytes will be used for Cyrillic characters.

However, it wouldn't be hard to compile a version of TELNET.EXE that translated Unicode characters for Code Page 866.  This just involves modifying this code: 
https://github.com/jhpyle/mTCP/blob/master/MTCP/APPS/TELNET/TELNETSC.CPP#L722
See
https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP866.TXT

**Comment by VasylSamoilov** [comment]
Yes, this noutf8.exe behaves as original mTCP telnet in both C and codepage 866. TERM is ansi. Works even better, as functional keys work now out of the box.

**Comment by jhpyle** [comment]
Hi @VasylSamoilov -- in the latest version, I added support for doing unicode translations to code page 866, among other code pages.  Instructions are in the README for how to modify your MTCP.CFG file to support alternate code pages.  You can try the directives in the `CP866` file in the `config` directory.  I think if you use this and set your locale to something like `uk_UA.UTF-8`, things should hopefully work correctly.
